name: 'Swan40 PCB CI/CD'

on:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kibot.yaml'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**.kibot.yaml'

jobs:
  export-pcb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: INTI-CMNB/KiBot@v2_k7
        with:
          config: configs/config.kibot.yaml
          dir: pcb/output
          schema: 'pcb/Swan40.kicad_sch'
          board: 'pcb/Swan40-rounded.kicad_pcb'
      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Swan40-pcb
          path: |
            pcb/output/
          if-no-files-found: warn
  export-left-plate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: INTI-CMNB/KiBot@v2_k7
        with:
          config: configs/config.kibot.yaml
          dir: lplate/output
          board: 'left-plate/left-plate.kicad_pcb'
      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Swan40-left-plate
          path: |
            lplate/output/
          if-no-files-found: warn
  export-right-plate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: INTI-CMNB/KiBot@v2_k7
        with:
          config: configs/config.kibot.yaml
          dir: rplate/output
          board: 'right-plate/right-plate.kicad_pcb'
      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Swan40-right-plate
          path: |
            rplate/output/
          if-no-files-found: warn
  export-plate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: INTI-CMNB/KiBot@v2_k7
        with:
          config: configs/config.kibot.yaml
          dir: plate/output
          board: 'plate/plate.kicad_pcb'
      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Swan40-plate
          path: |
            plate/output/
          if-no-files-found: warn
