name: 'Swan40 PCB CI/CD'

on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'

jobs:
  export_pcb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: INTI-CMNB/KiBot@v2_k7
        with:
          config:
